In [5]:
import numpy as np
import pandas as pd

In [6]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv("tmdb_5000_credits.csv")

In [7]:
movies = movies.merge(credits,on = 'title')

In [8]:
# genres
# id
# keywords
# title
# overview
# cast
# crew
movies = movies[["movie_id","genres","id","keywords","title","overview","cast","crew"]]

In [9]:
movies.isnull().sum()

movie_id    0
genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace = True)

In [11]:
movies.duplicated().sum()

np.int64(0)

In [12]:
import ast
def rearange(obj):
    list = []
    for i in ast.literal_eval(obj):
        list.append(i['name'])
    return list

In [13]:
movies["genres"] = movies["genres"].apply(rearange)
movies["keywords"] = movies["keywords"].apply(rearange)

In [14]:
def convert(obj):
    list = []
    a = 3
    for i in ast.literal_eval(obj):
        if a <= 0:
            break
        list.append(i['character'])
        a = a-1
    return list

In [15]:
movies['cast'] = movies['cast'].apply(convert)

In [16]:
def direct(obj):
    list = []
    for i in ast.literal_eval(obj):
        if i['job'] == "Director":
            list.append(i["name"])
    return list

In [17]:
movies["crew"] = movies["crew"].apply(direct)

In [18]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [19]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())

In [20]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [21]:
movies.head()

,movie_id,genres,id,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[JakeSully, Neytiri, Dr.GraceAugustine]",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[CaptainJackSparrow, WillTurner, ElizabethSwann]",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[JamesBond, Blofeld, Madeleine]",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[JohnCarter, DejahThoris, Sola]",[AndrewStanton]

In [22]:
movies['tags'] = movies['overview']+movies['genres']+ movies['keywords'] + movies['cast'] + movies['crew']

In [23]:
df = movies[['movie_id','title', 'tags']]

In [24]:
df["tags"] = df["tags"].apply(lambda x:" ".join(x))

C:\Users\Asus\AppData\Local\Temp\ipykernel_13408\330794017.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tags"] = df["tags"].apply(lambda x:" ".join(x))

In [25]:
df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JakeSully Neytiri Dr.GraceAugustine JamesCameron'

In [26]:
df['tags'] = df['tags'].apply(lambda x: x.lower())

C:\Users\Asus\AppData\Local\Temp\ipykernel_13408\4276611149.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x: x.lower())

In [27]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [28]:
 import nltk

In [29]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [30]:
def super(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [31]:
df["tags"] = df["tags"].apply(super)

C:\Users\Asus\AppData\Local\Temp\ipykernel_13408\3801135816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tags"] = df["tags"].apply(super)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(max_features = 5000,stop_words = 'english')

In [33]:
vectors = cv.fit_transform(df["tags"]).toarray()

In [34]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [35]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'],
      shape=(5000,), dtype=object)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
similarity = cosine_similarity(vectors)

In [38]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [40]:
import pickle
pickled = pickle.dump(df.to_dict(),open('movies_dict.pkl','wb'))

In [41]:
pickled = pickle.dump(similarity,open('similarity.pkl','wb'))